modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "granularshinies"
version = "1.5-forge-1.0.1"
displayName = "Cobblemon Granular Shinies"
description = '''
Customize shiny rates on a Pokemon Properties level.
'''

[[dependencies.granularshinies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.granularshinies]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.granularshinies]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.0,)"
ordering = "NONE"
side = "BOTH"
